language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer update

script:
 - phpunit --coverage-text --configuration tests/phpunit.xml

notifications:
  email: christoph@renepardon.de


