<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PhMagick\Adapter\Text'             => __DIR__ . '/src/PhMagick/Adapter/Text.php',
    'PhMagick\Adapter\Resize'           => __DIR__ . '/src/PhMagick/Adapter/Resize.php',
    'PhMagick\Adapter\AdapterAbstract'  => __DIR__ . '/src/PhMagick/Adapter/AdapterAbstract.php',
    'PhMagick\Adapter\Convert'          => __DIR__ . '/src/PhMagick/Adapter/Convert.php',
    'PhMagick\Adapter\Decorations'      => __DIR__ . '/src/PhMagick/Adapter/Decorations.php',
    'PhMagick\Adapter\AdapterInterface' => __DIR__ . '/src/PhMagick/Adapter/AdapterInterface.php',
    'PhMagick\Adapter\Enhancements'     => __DIR__ . '/src/PhMagick/Adapter/Enhancements.php',
    'PhMagick\Adapter\Cli'              => __DIR__ . '/src/PhMagick/Adapter/Cli.php',
    'PhMagick\Adapter\Transform'        => __DIR__ . '/src/PhMagick/Adapter/Transform.php',
    'PhMagick\Adapter\Compose'          => __DIR__ . '/src/PhMagick/Adapter/Compose.php',
    'PhMagick\Adapter\Color'            => __DIR__ . '/src/PhMagick/Adapter/Color.php',
    'PhMagick\Adapter\Crop'             => __DIR__ . '/src/PhMagick/Adapter/Crop.php',
    'PhMagick\Adapter\AdapterTrait'     => __DIR__ . '/src/PhMagick/Adapter/AdapterTrait.php',
    'PhMagick\Module'                   => __DIR__ . '/src/PhMagick/Module.php',
    'PhMagick\TextObject'               => __DIR__ . '/src/PhMagick/TextObject.php',
    'PhMagick\History'                  => __DIR__ . '/src/PhMagick/History.php',
    'PhMagick\PhMagick'                 => __DIR__ . '/src/PhMagick/PhMagick.php',
    'PhMagick\Gravity'                  => __DIR__ . '/src/PhMagick/Gravity.php',
);